# Generated by Django 3.2.9 on 2024-09-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='letter_attachments/'),
        ),
    ]
